# Site settings
title: Cameron Robinson
description: 'Web Developer | Writer | Photographer'
url: 'http://cameroncrobinson.com'
baseurl: ''
google_analytics: 'UA-96298015-4'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Cameron Robinson'
  email: robinson.cameron90@gmail.com
  twitter_username:
  facebook_username:
  github_username:  cameroncrobinson
  linkedin_username:  cameron-webdev
  portfoilio_link: https://cameroncrobinson.myportfolio.com/
  photo_site: https://www.dropdeadphoto.com/
  medium_blog: https://medium.com/@cameronrobinson_37662
  codepen: https://codepen.io/cameroncrobinson

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
